version: '2'
services:
  investacoresvc-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/investacoresvc/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=investacoresvc
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
